version: '3.8'
services:
  backend:
    container_name: proyecto_backend
    build: ProyectoBackend
    depends_on:
      - database
  frontend:
    container_name: proyecto_frontend
    build: ProyectoFrontend
    ports:
      - 80:80
    volumes:
      - ./ProyectoFrontend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend  
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
